name: Advanced Usage

on: [push, pull_request]

env:
  FILE_NAME: react-interview-questions

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04    
    steps:      
      - uses: actions/checkout@v2    

      - name: Create output directory
        run: |
          mkdir output  # create output dir          
      
      - name: Create PDF
        uses: docker://pandoc/latex:2.9              
        with:
          args: --pdf-engine=xelatex --output=output/${{env.FILE_NAME}}.pdf README.md

      - name: Create epub
        uses: docker://pandoc/latex:2.9      
        with:
          args: --output=output/${{env.FILE_NAME}}.epub README.md
      
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output